// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIHjqUq8eZJr6Im8QVJfSBb3wxZ_cEARg',
    appId: '1:167923583809:web:9065d5bbab583d3a876fc0',
    messagingSenderId: '167923583809',
    projectId: 'fir-cli-1a689',
    authDomain: 'fir-cli-1a689.firebaseapp.com',
    databaseURL: 'https://fir-cli-1a689-default-rtdb.firebaseio.com',
    storageBucket: 'fir-cli-1a689.appspot.com',
    measurementId: 'G-J9DN9VMCTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEHl3TkKFjiQoJ0pbkIczirdWCtVx2ouo',
    appId: '1:167923583809:android:23259dad67b52893876fc0',
    messagingSenderId: '167923583809',
    projectId: 'fir-cli-1a689',
    databaseURL: 'https://fir-cli-1a689-default-rtdb.firebaseio.com',
    storageBucket: 'fir-cli-1a689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Px-vPnR1Quz7qvDnpoEeVv1jZZgZ5N0',
    appId: '1:167923583809:ios:1eb76b8c0da3a17e876fc0',
    messagingSenderId: '167923583809',
    projectId: 'fir-cli-1a689',
    databaseURL: 'https://fir-cli-1a689-default-rtdb.firebaseio.com',
    storageBucket: 'fir-cli-1a689.appspot.com',
    androidClientId: '167923583809-ndf88vitqpoul77k5ltrcgvobm4vv4fc.apps.googleusercontent.com',
    iosClientId: '167923583809-9ins52qa11qijrns33104bouii7ilu1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fire',
  );
}
